### ISSUE TITLE
War does not run in Tomee

### ISSUE THREAD

**Issue by PatrickMcAfee** [torquebox/torquebox#220]
Hey folks, I'm attempting to run Torquebox 4.0.0.beta1 on jruby-9.0.0.0 and I'm getting errors when deploying to TomEE. Are the generated wars meant to be runnable on other J2EE servers than Wildfly?  Is there any way to configure the listener in web.xml to be generic instead of relying on Wildfly? (other than unzipping, editing, and rezipping, of course)

Relevant error:
```
2015-08-18 05:28:33,931 [localhost-startStop-1] INFO  OpenEJB.startup- Deployed Application(path=/opt/tomee/webapps/ROOT)
2015-08-18 05:28:34,022 [localhost-startStop-1] ERROR org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]- Error configuring application listener of class org.projectodd.wunderboss.wildfly.ServletListener
java.lang.ClassNotFoundException: org.projectodd.wunderboss.wildfly.ServletListener
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1720)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1571)
	at org.apache.tomee.catalina.LazyStopWebappClassLoader.loadClass(LazyStopWebappClassLoader.java:129)
	at org.apache.tomee.catalina.JavaeeInstanceManager.newInstance(JavaeeInstanceManager.java:66)
	at org.apache.tomee.catalina.JavaeeInstanceManager.newInstance(JavaeeInstanceManager.java:61)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4907)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-08-18 05:28:34,031 [localhost-startStop-1] ERROR org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]- Skipped installing application listeners due to previous error(s)
```

**Comment by bbrowning** [comment]
Right now we don't expect the war to run in anything but WildFly. It should technically be possible to run inside other containers and we have some of the code necessary to do so in place but not all of it. We've talked about making the wars work in anything from vanilla Tomcat, to Jetty, TomEE, etc. It hasn't been a high priority, but is something I'd like to look at more at some point.

With that said, the error you're getting is interesting. We supply that org.projectodd.wunderboss.wildfly.ServletListener class, so I'm surprised it can't be found.

**Comment by PatrickMcAfee** [comment]
If it helps, the war was built using --no-include-jruby and --no-bundle-gem  options - I was using a local instance of jruby with the gems installed.
