### ISSUE TITLE
Incompatible with JRuby 9.1.0.0

### ISSUE THREAD

**Issue by t3hk0d3** [torquebox/torquebox#238]
```
java.lang.VerifyError: class org.projectodd.wunderboss.rack.RackEnvironmentHash overrides final method to_s19.(Lorg/jruby/runtime/ThreadContext;)Lorg/jruby/runtime/builtin/IRubyObject;
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_66]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_66]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_66]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_66]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_66]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_66]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_66]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_66]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
        at org.projectodd.wunderboss.rack.RackEnvironment.getEnv(RackEnvironment.java:94) ~[wunderboss-rack.jar:na]
        at org.projectodd.wunderboss.rack.RackApplication.call(RackApplication.java:50) ~[wunderboss-rack.jar:na]
        at org.projectodd.wunderboss.rack.RackHandler.handleRequest(RackHandler.java:36) ~[wunderboss-rack.jar:na]
        at io.undertow.server.session.SessionAttachmentHandler.handleRequest(SessionAttachmentHandler.java:68) ~[undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) ~[undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759) ~[undertow-core-1.1.0.Final.jar:1.1.0.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
```

https://github.com/torquebox/torquebox/blob/master/web/ext/wunderboss-rack/org/projectodd/wunderboss/rack/RackEnvironmentHash.java#L212

https://github.com/jruby/jruby/wiki/JRuby-9.1.0.0-Release-Notes#java-integration

**Comment by t3hk0d3** [comment]
Simple fix:

Remove ``to_s`` and ``to_s19`` overriding in ``RackEnvironmentHash`` because ``inspect`` is overridden as well and just called by underlying ``org.jruby.RubyHash`` in both 9.0.5.0 and 9.1.0.0:

https://github.com/jruby/jruby/blob/9.0.5.0/core/src/main/java/org/jruby/RubyHash.java#L906
https://github.com/jruby/jruby/blob/9.1.0.0/core/src/main/java/org/jruby/RubyHash.java#L997
